project:
  whitepaper:
    url: "https://example.org/whitepaper.pdf"
  roadmap:
    milestones:
      - title: Project started
        date: 2022-04-05
        status: completed
        description: Brief description ipsum dolor sit amet, consectetur adipiscing elit...
      - title: Testnet 1
        date: 2022-04-05
        status: completed
        description: Brief description ipsum dolor sit amet, consectetur adipiscing elit...
      - title: Keplr Integration
        date: 2022-06-05
        status: active
        description: Brief description ipsum dolor sit amet, consectetur adipiscing elit...
      - title: Mainnet
        date: 2022-07-05
        status: expected
        description: Brief description ipsum dolor sit amet, consectetur adipiscing elit...
  tokenomics:
    distribution:
      - title: Marketing
        share: 25%
  team:
    members:
      - name: Bob
        title: CEO
        description: Bio lorem consequat efficitur iaculis. Nam eu tincidunt nunc...
  links:
    - type: twitter
      url: https://twitter.com/example
      display: true
    - type: discord
      url: https://discord.com
      display: true
    - type: telegram
      url: https://web.telegram.org/z/
      display: true
